# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "gd2-ffi"
  s.version = IO.read("./VERSION")

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Patrik Stenmark"]
  s.date = "2013-02-07"
  s.description = "gd2-ffi is ruby bindings for gd2, implemented with ffi"
  s.email = "patrik.stenmark@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "gd2-ffi.gemspec",
    "lib/gd2-ffi.rb",
    "lib/gd2/canvas.rb",
    "lib/gd2/cgd2.rb",
    "lib/gd2/color.rb",
    "lib/gd2/font.rb",
    "lib/gd2/image.rb",
    "spec/Vera.ttf",
    "spec/canvas_spec.rb",
    "spec/color_spec.rb",
    "spec/image_spec.rb",
    "spec/spec_helper.rb",
    "test.rb"
  ]
  s.homepage = "http://github.com/spatrik/gd2-ffi"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "gd2-ffi is ruby bindings for gd2, implemented with ffi"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

